### ISSUE TITLE
Why is there a blank line here?

### ISSUE THREAD

**Issue by itldg** [zvakanaka/curl-string#8]
https://github.com/zvakanaka/curl-string/blob/88ee5496065f10c48ea4cbc4d024cc0353677b8f/index.js#L27

If modified to:

```
let curl = `curl --request ${method} \\\n--url ${url}${
```

Is it better?

**Comment by zvakanaka** [comment]
Thank you for requesting this. Here is the PR. https://github.com/zvakanaka/curl-string/pull/9
